interface FunnelStage { label: string; value: number }
interface AcademicFunnelProps { title: string; stages: FunnelStage[]; tone: 'blue' | 'orange' }

export function AcademicFunnel({ title, stages, tone }: AcademicFunnelProps) {
  const max = Math.max(...stages.map((stage) => stage.value), 1)
  const heights = stages.map((stage) => 42 + (stage.value / max) * 78)
  const fill = tone === 'blue' ? '#1689b4' : '#e78305'
  const edge = tone === 'blue' ? '#0e476c' : '#6d3900'
  const pattern = `funnel-pattern-${tone}`
  const points = stages.map((_, index) => 60 + index * (880 / Math.max(stages.length - 1, 1)))
  return <article className="glass-card rounded-[1.25rem] p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#8a716f]">Visualización del ciclo</p><h3 className="mt-2 font-semibold tracking-tight text-[#1a1c1a] dark:text-white">{title}</h3><p className="mt-1 text-xs text-[#8a716f]">Evolución por etapa académica</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider ${tone === 'blue' ? 'bg-sky-100 text-sky-800 dark:bg-sky-950/50 dark:text-sky-200' : 'bg-orange-100 text-orange-800 dark:bg-orange-950/50 dark:text-orange-200'}`}>Actual</span></div><div className="mt-5 overflow-x-auto pb-1"><svg className="mx-auto min-w-[620px]" viewBox="0 0 1000 270" role="img" aria-label={`Embudo horizontal de ${title}`}><defs><pattern id={pattern} width="10" height="10" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="10" height="10" fill={fill} /><path d="M0 0V10" stroke="#fff" strokeOpacity=".28" strokeWidth="2" /></pattern></defs>{stages.map((stage, index) => { const x = points[index]; const next = points[index + 1] ?? 980; const top = 135 - heights[index]; const bottom = 135 + heights[index]; const nextTop = 135 - (heights[index + 1] ?? heights[index] * .58); const nextBottom = 135 + (heights[index + 1] ?? heights[index] * .58); const d = `M ${x} ${top} C ${x + 45} ${top}, ${next - 45} ${nextTop}, ${next} ${nextTop} L ${next} ${nextBottom} C ${next - 45} ${nextBottom}, ${x + 45} ${bottom}, ${x} ${bottom} Z`; const percent = Math.round((stage.value / max) * 100); return <g key={stage.label}><path d={d} fill={`url(#${pattern})`} stroke={edge} strokeWidth="7" strokeLinejoin="round" /><rect x={x + (next - x) / 2 - 38} y="118" width="76" height="34" rx="18" fill="#fff1f4" /><text x={x + (next - x) / 2} y="140" textAnchor="middle" fontSize="16" fontWeight="700" fill="#201619">{percent}%</text><text x={x + (next - x) / 2} y="35" textAnchor="middle" fontSize="14" fontWeight="700" fill="currentColor">{stage.value.toLocaleString('es')}</text><text x={x + (next - x) / 2} y="235" textAnchor="middle" fontSize="13" fill="currentColor">{stage.label}</text></g> })}</svg></div></article>
}
