"""Migracion de Tabla Docentes & Carreras con su Auditoria

Revision ID: 0c3f7a709e30
Revises: ddcb28236d80
Create Date: 2026-10-02 23:21:08.068054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3f7a709e30'
down_revision: Union[str, Sequence[str], None] = 'ddcb28236d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
