"""crear tablas docentes y carreras

Revision ID: 68c24666da7c
Revises: 69d6a3e4b470
Create Date: 2026-10-03 01:29:41.381528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c24666da7c'
down_revision: Union[str, Sequence[str], None] = '69d6a3e4b470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carreras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('duracion_anios', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_carreras_id'), 'carreras', ['id'], unique=False)
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_empleado', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('especialidad', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('numero_empleado')
    )
    op.create_index(op.f('ix_docentes_id'), 'docentes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docentes_id'), table_name='docentes')
    op.drop_table('docentes')
    op.drop_index(op.f('ix_carreras_id'), table_name='carreras')
    op.drop_table('carreras')
    # ### end Alembic commands ###
