import { EntityPage, StatusBadge } from '../components/crud/EntityPage'
import { asignaturasApi } from '../services/api'
import type { Asignatura, AsignaturaPayload } from '../types/api'
import { useAcademicLabels } from '../hooks/useAcademicLabels'
const empty: AsignaturaPayload = { codigo: '', nombre: '', unidades_valorativas: 3, carrera_id: 1, requisito_id: null, activo: true }
export function AsignaturasPage() {
  const labels = useAcademicLabels()
  return <EntityPage<Asignatura, AsignaturaPayload> title="Asignaturas" singular="Asignatura" newLabel="Nueva asignatura" description="Administra el plan académico y sus requisitos." service={asignaturasApi} emptyPayload={empty} toPayload={(item) => ({ codigo: item.codigo, nombre: item.nombre, unidades_valorativas: item.unidades_valorativas, carrera_id: item.carrera_id, requisito_id: item.requisito_id, activo: item.activo })} searchableText={(item) => `${item.codigo} ${item.nombre} ${labels.carreras[item.carrera_id] ?? ''}`} columns={[{ label: 'Código', render: (item) => <strong>{item.codigo}</strong> }, { label: 'Nombre', render: (item) => item.nombre }, { label: 'Unidades', render: (item) => item.unidades_valorativas }, { label: 'Carrera', render: (item) => labels.carreras[item.carrera_id] ?? `Carrera #${item.carrera_id}` }, { label: 'Estado', render: (item) => <StatusBadge active={item.activo} /> }]} fields={[{ key: 'codigo', label: 'Código' }, { key: 'nombre', label: 'Nombre' }, { key: 'unidades_valorativas', label: 'Unidades valorativas', type: 'number', min: 1, max: 20 }, { key: 'carrera_id', label: 'Carrera', type: 'select', valueType: 'number', options: labels.carreraOptions }, { key: 'requisito_id', label: 'Requisito', type: 'select', valueType: 'number', options: [{ label: 'Sin requisito', value: '' }, ...labels.asignaturaOptions], required: false }, { key: 'activo', label: 'Asignatura activa', type: 'checkbox' }]} />
}
