import { EntityPage } from '../components/crud/EntityPage'
import { matriculasApi } from '../services/api'
import type { Matricula, MatriculaPayload } from '../types/api'
import { UserRound } from 'lucide-react'
import { useAcademicLabels } from '../hooks/useAcademicLabels'
const empty: MatriculaPayload = { estudiante_id: 1, seccion_id: 1, fecha_matricula: new Date().toISOString().slice(0, 10), estado: 'ACTIVA' }
export function MatriculasPage() {
  const labels = useAcademicLabels()
  return <EntityPage<Matricula, MatriculaPayload> title="Matrículas" singular="Matrícula" newLabel="Nueva matrícula" description="Administra la inscripción de estudiantes en secciones." service={matriculasApi} emptyPayload={empty} toPayload={(item) => ({ estudiante_id: item.estudiante_id, seccion_id: item.seccion_id, fecha_matricula: item.fecha_matricula, estado: item.estado })} searchableText={(item) => `${labels.estudiantes[item.estudiante_id] ?? ''} ${labels.secciones[item.seccion_id] ?? ''} ${item.estado}`} columns={[{ label: 'Estudiante', render: (item) => <span className="inline-flex items-center gap-2"><UserRound className="h-4 w-4 text-sage-600" /><strong>{labels.estudiantes[item.estudiante_id] ?? `Estudiante #${item.estudiante_id}`}</strong></span> }, { label: 'Sección', render: (item) => labels.secciones[item.seccion_id] ?? `Sección #${item.seccion_id}` }, { label: 'Fecha', render: (item) => item.fecha_matricula }, { label: 'Estado', render: (item) => item.estado }]} fields={[{ key: 'estudiante_id', label: 'Estudiante', type: 'select', valueType: 'number', options: labels.estudianteOptions }, { key: 'seccion_id', label: 'Sección', type: 'select', valueType: 'number', options: labels.seccionOptions }, { key: 'fecha_matricula', label: 'Fecha de matrícula', type: 'date' }, { key: 'estado', label: 'Estado', type: 'select', options: [{ label: 'Activa', value: 'ACTIVA' }, { label: 'Cancelada', value: 'CANCELADA' }, { label: 'Aprobada', value: 'APROBADA' }, { label: 'Reprobada', value: 'REPROBADA' }] }]} />
}
