import { BookOpen, UserRound } from 'lucide-react'
import { EntityPage } from '../components/crud/EntityPage'
import { useAcademicLabels } from '../hooks/useAcademicLabels'
import { seccionesApi } from '../services/api'
import type { Seccion, SeccionPayload } from '../types/api'
const empty: SeccionPayload = { codigo: '', asignatura_id: 1, docente_id: 1, periodo_id: 1, aula_id: 1, dias: 'LUN-MIE', hora_inicio: '08:00', hora_fin: '10:00', cupo_maximo: 30, estado: 'ABIERTA' }
export function SeccionesPage() {
  const labels = useAcademicLabels()
  return <EntityPage<Seccion, SeccionPayload> title="Secciones" singular="Sección" newLabel="Nueva sección" description="Organiza horarios, docentes y espacios de cada clase." service={seccionesApi} emptyPayload={empty} toPayload={(item) => ({ codigo: item.codigo, asignatura_id: item.asignatura_id, docente_id: item.docente_id, periodo_id: item.periodo_id, aula_id: item.aula_id, dias: item.dias, hora_inicio: item.hora_inicio, hora_fin: item.hora_fin, cupo_maximo: item.cupo_maximo, estado: item.estado })} searchableText={(item) => `${item.codigo} ${labels.asignaturas[item.asignatura_id] ?? ''} ${labels.docentes[item.docente_id] ?? ''} ${labels.periodos[item.periodo_id] ?? ''}`} columns={[{ label: 'Código', render: (item) => <strong>{item.codigo}</strong> }, { label: 'Clase', render: (item) => <span className="inline-flex items-center gap-2"><BookOpen className="h-4 w-4 text-sage-600" />{labels.asignaturas[item.asignatura_id] ?? `Asignatura #${item.asignatura_id}`}</span> }, { label: 'Docente', render: (item) => <span className="inline-flex items-center gap-2"><UserRound className="h-4 w-4 text-sage-600" />{labels.docentes[item.docente_id] ?? `Docente #${item.docente_id}`}</span> }, { label: 'Periodo', render: (item) => labels.periodos[item.periodo_id] ?? `Periodo #${item.periodo_id}` }, { label: 'Horario', render: (item) => `${item.dias} ${item.hora_inicio}-${item.hora_fin}` }, { label: 'Estado', render: (item) => item.estado }]} fields={[{ key: 'codigo', label: 'Código' }, { key: 'asignatura_id', label: 'Asignatura', type: 'select', valueType: 'number', options: labels.asignaturaOptions }, { key: 'docente_id', label: 'Docente', type: 'select', valueType: 'number', options: labels.docenteOptions }, { key: 'periodo_id', label: 'Periodo', type: 'select', valueType: 'number', options: labels.periodoOptions }, { key: 'aula_id', label: 'Aula', type: 'select', valueType: 'number', options: labels.aulaOptions }, { key: 'dias', label: 'Días' }, { key: 'hora_inicio', label: 'Hora de inicio' }, { key: 'hora_fin', label: 'Hora de cierre' }, { key: 'cupo_maximo', label: 'Cupo máximo', type: 'number', min: 1 }, { key: 'estado', label: 'Estado', type: 'select', options: [{ label: 'Abierta', value: 'ABIERTA' }, { label: 'Cerrada', value: 'CERRADA' }, { label: 'Cancelada', value: 'CANCELADA' }] }]} statusOptions={[{ value: 'abierta', label: 'Abiertas' }, { value: 'cerrada', label: 'Cerradas' }, { value: 'cancelada', label: 'Canceladas' }]} />
}
